id: Recorded Future CVE Intelligence
version: -1
name: Recorded Future CVE Intelligence
description: CVE Enrichment using Recorded Future Intelligence
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
    type: start
    task:
      id: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 2b22eb54-802e-4d08-88da-3435a0e282da
    type: condition
    task:
      id: 2b22eb54-802e-4d08-88da-3435a0e282da
      version: -1
      name: Is there a CVE ID to enrich?
      description: Checks whether the playbook's input contains at least one CVE name
        to enrich.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.CVE
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 9b1db93f-3933-43ee-89cd-df000c5047a2
    type: title
    task:
      id: 9b1db93f-3933-43ee-89cd-df000c5047a2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "26":
    id: "26"
    taskid: 4729ec6c-7996-4e59-88c7-f9621b41d451
    type: condition
    task:
      id: 4729ec6c-7996-4e59-88c7-f9621b41d451
      version: -1
      name: Is Recorded Future API enabled?
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Recorded Future
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: 63c3eaf7-343a-4c44-842f-c366ef24f5ac
    type: regular
    task:
      id: 63c3eaf7-343a-4c44-842f-c366ef24f5ac
      version: -1
      name: Get CVE ID intelligence from Recorded Future
      description: Get threat intelligence for an IP, domain, cve, url or file.
      script: Recorded Future v2|||recordedfuture-intelligence
      type: regular
      iscommand: true
      brand: Recorded Future v2
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      entity:
        simple: ${inputs.CVE}
      entity_type:
        simple: cve
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 8075d9ed-0723-4435-8018-09dc88e18081
    type: title
    task:
      id: 8075d9ed-0723-4435-8018-09dc88e18081
      version: -1
      name: Enrich Using Recorded Future API
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: CVE
  value:
    complex:
      root: CVE
      accessor: ID
  required: false
  description: The CVE ID to enrich.
  playbookInputQuery:
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
- contextPath: DBotScore.Type
  description: Indicator type
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
- contextPath: DBotScore.Score
  description: The actual score
- contextPath: CVE.ID
  description: Vulnerability name
- contextPath: RecordedFuture.CVE.criticality
  description: Risk Criticality
- contextPath: RecordedFuture.CVE.criticalityLabel
  description: Risk Criticality Label
- contextPath: RecordedFuture.CVE.riskString
  description: Risk String
- contextPath: RecordedFuture.CVE.riskSummary
  description: Risk Summary
- contextPath: RecordedFuture.CVE.rules
  description: Risk Rules
- contextPath: RecordedFuture.CVE.score
  description: Risk Score
- contextPath: RecordedFuture.CVE.firstSeen
  description: Evidence First Seen
- contextPath: RecordedFuture.CVE.lastSeen
  description: Evidence Last Seen
- contextPath: RecordedFuture.CVE.intelCard
  description: Recorded Future Intelligence Card URL
- contextPath: RecordedFuture.CVE.type
  description: Entity Type
- contextPath: RecordedFuture.CVE.name
  description: Entity
- contextPath: RecordedFuture.CVE.id
  description: Recorded Future Entity ID
- contextPath: RecordedFuture.CVE.metrics.type
  description: Recorded Future Metrics Type
- contextPath: RecordedFuture.CVE.metrics.value
  description: Recorded Future Metrics Value
- contextPath: RecordedFuture.CVE.threatLists.description
  description: Recorded Future Threat List Description
- contextPath: RecordedFuture.CVE.threatLists.id
  description: Recorded Future Threat List ID
- contextPath: RecordedFuture.CVE.threatLists.name
  description: Recorded Future Threat List Name
- contextPath: RecordedFuture.CVE.threatLists.type
  description: Recorded Future Threat List Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttacker.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttacker.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttacker.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttacker.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTarget.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTarget.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTarget.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTarget.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedThreatActor.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedThreatActor.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedThreatActor.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedThreatActor.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalware.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalware.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalware.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalware.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCyberVulnerability.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCyberVulnerability.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCyberVulnerability.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCyberVulnerability.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedIpAddress.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedIpAddress.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedIpAddress.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedIpAddress.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedInternetDomainName.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedInternetDomainName.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedInternetDomainName.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedInternetDomainName.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedProduct.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedProduct.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedProduct.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedProduct.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCountries.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCountries.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCountries.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCountries.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedHash.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedHash.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedHash.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedHash.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTechnology.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTechnology.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTechnology.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedTechnology.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedEmailAddress.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedEmailAddress.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedEmailAddress.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedEmailAddress.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttackVector.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttackVector.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttackVector.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedAttackVector.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalwareCategory.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalwareCategory.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalwareCategory.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedMalwareCategory.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedOperations.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedOperations.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedOperations.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedOperations.type
  description: Recorded Future Related Type
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCompany.count
  description: Recorded Future Related Count
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCompany.id
  description: Recorded Future Related ID
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCompany.name
  description: Recorded Future Related Name
- contextPath: RecordedFuture.CVE.relatedEntities.RelatedCompany.type
  description: Recorded Future Related Type
fromversion: 5.0.0
tests:
- No tests (auto formatted)
