id: Recorded Future Domain Reputation
version: -1
name: Recorded Future Domain Reputation
description: Domain reputation using Recorded Future SOAR Enrichment
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
    type: start
    task:
      id: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 3c6fe423-8215-4bd0-8bf5-c57c35889637
    type: condition
    task:
      id: 3c6fe423-8215-4bd0-8bf5-c57c35889637
      version: -1
      name: Is there a domain to get reputation of?
      description: Checks whether the playbook's input contains at least one domain
        name to get reputation of.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Domain
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 9b1db93f-3933-43ee-89cd-df000c5047a2
    type: title
    task:
      id: 9b1db93f-3933-43ee-89cd-df000c5047a2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "26":
    id: "26"
    taskid: 4729ec6c-7996-4e59-88c7-f9621b41d451
    type: condition
    task:
      id: 4729ec6c-7996-4e59-88c7-f9621b41d451
      version: -1
      name: Is Recorded Future API enabled?
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Recorded Future
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: 53bddf1a-a9f2-454c-8837-81e27976c8a7
    type: regular
    task:
      id: 53bddf1a-a9f2-454c-8837-81e27976c8a7
      version: -1
      name: Get domain reputation from Recorded Future
      description: Get a quick indicator of the risk associated with a domain.
      script: Recorded Future v2|||domain
      type: regular
      iscommand: true
      brand: Recorded Future v2
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
          transformers:
          - operator: uniq
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 8075d9ed-0723-4435-8018-09dc88e18081
    type: title
    task:
      id: 8075d9ed-0723-4435-8018-09dc88e18081
      version: -1
      name: Get reputation using Recorded Future API
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Domain
  value:
    complex:
      root: Domain
      accessor: Name
  required: false
  description: The domain name to get reputation of.
  playbookInputQuery:
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
- contextPath: DBotScore.Type
  description: Indicator type
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
- contextPath: DBotScore.Score
  description: The actual score
- contextPath: Domain.Malicious.Vendor
  description: For malicious Domains, the vendor that made the decision
- contextPath: Domain.Malicious.Description
  description: For malicious Domains, the reason that the vendor made the decision
- contextPath: Domain.name
  description: Domain name
- contextPath: RecordedFuture.Domain.riskScore
  description: Recorded Future Domain Risk Score
- contextPath: RecordedFuture.Domain.riskLevel
  description: Recorded Future Domain Risk Level
- contextPath: RecordedFuture.Domain.Evidence.rule
  description: Recorded Risk Rule Name
- contextPath: RecordedFuture.Domain.Evidence.mitigation
  description: Recorded Risk Rule Mitigation
- contextPath: RecordedFuture.Domain.Evidence.description
  description: Recorded Risk Rule description
- contextPath: RecordedFuture.Domain.Evidence.timestamp
  description: Recorded Risk Rule timestamp
- contextPath: RecordedFuture.Domain.Evidence.level
  description: Recorded Risk Rule Level
- contextPath: RecordedFuture.Domain.Evidence.ruleid
  description: Recorded Risk Rule ID
- contextPath: RecordedFuture.Domain.name
  description: Domain name
- contextPath: RecordedFuture.Domain.maxRules
  description: Maximum count of Recorded Future Domain Risk Rules
- contextPath: RecordedFuture.Domain.ruleCount
  description: Number of triggered Recorded Future Domain Risk Rules
fromversion: 5.0.0
tests:
- No tests (auto formatted)
