id: Recorded Future Phishing Threat Assessment
version: -1
name: Recorded Future Phishing Threat Assessment
description: Threat Assessment using the Recorded Future SOAR Triage API and the Phishing
  context.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f546bc56-764b-4d58-8425-9d3c7ffae3d6
    type: start
    task:
      id: f546bc56-764b-4d58-8425-9d3c7ffae3d6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: fbbf54f0-9cee-4e52-8d0e-230ec504541c
    type: condition
    task:
      id: fbbf54f0-9cee-4e52-8d0e-230ec504541c
      version: -1
      name: Is there anything to assess?
      description: Checks whether the playbook's input contains at least one domain
        name to enrich.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.CVE
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.IP
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.MD5
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.SHA1
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.SHA256
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: inputs.Domain
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 6f48ecf2-ba1a-4f6a-8f76-edafe2bcd777
    type: title
    task:
      id: 6f48ecf2-ba1a-4f6a-8f76-edafe2bcd777
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1005
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "26":
    id: "26"
    taskid: a3280663-519e-420c-8c8f-91a2ecbab334
    type: condition
    task:
      id: a3280663-519e-420c-8c8f-91a2ecbab334
      version: -1
      name: Is Recorded Future API enabled?
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Recorded Future
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: 279e9591-7bbb-419c-81ec-892ad0d026b6
    type: regular
    task:
      id: 279e9591-7bbb-419c-81ec-892ad0d026b6
      version: -1
      name: Get Threat Assessment from Recorded Future
      description: Get an indicator of the risk based on context.
      script: Recorded Future v2|||recordedfuture-threat-assessment
      type: regular
      iscommand: true
      brand: Recorded Future v2
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      context:
        simple: phishing
      cve:
        simple: ${inputs.CVE}
      domain:
        simple: ${inputs.Domain}
      file:
        simple: ${inputs.MD5},${inputs.SHA1},${inputs.SHA256}
      ip:
        simple: ${inputs.IP}
      url:
        simple: ${inputs.URL}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 1cfef537-3322-4cab-8577-6f25ff78857c
    type: title
    task:
      id: 1cfef537-3322-4cab-8577-6f25ff78857c
      version: -1
      name: Threat Assessment Using Recorded Future API
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57
    },
    "paper": {
      "dimensions": {
        "height": 1020,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: CVE
  value:
    complex:
      root: CVE
      accessor: ID
      transformers:
      - operator: uniq
  required: false
  description: "CVE"
  playbookInputQuery:
- key: IP
  value:
    complex:
      root: IP
      accessor: Address
      transformers:
      - operator: uniq
  required: false
  description: "IP Address"
  playbookInputQuery:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
      transformers:
      - operator: uniq
  required: false
  description: "URL"
  playbookInputQuery:
- key: MD5
  value:
    complex:
      root: File
      accessor: MD5
      transformers:
      - operator: uniq
  required: false
  description: "MD5"
  playbookInputQuery:
- key: SHA1
  value:
    complex:
      root: File
      accessor: SHA1
      transformers:
      - operator: uniq
  required: false
  description: "SHA-1"
  playbookInputQuery:
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
      transformers:
      - operator: uniq
  required: false
  description: "SHA-256"
  playbookInputQuery:
- key: Domain
  value:
    complex:
      root: Domain
      accessor: Name
      transformers:
      - operator: uniq
  required: false
  description: "Domain"
  playbookInputQuery:
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
- contextPath: DBotScore.Type
  description: Indicator type
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
- contextPath: DBotScore.Score
  description: The actual score
- contextPath: RecordedFuture.verdict
  description: Recorded Future verdict
- contextPath: RecordedFuture.context
  description: Threat Assessment Context
- contextPath: RecordedFuture.riskScore
  description: Recorded Future Max Score
- contextPath: RecordedFuture.Entities.id
  description: Entity ID
- contextPath: RecordedFuture.Entities.name
  description: Entity Name
- contextPath: RecordedFuture.Entities.type
  description: Entity Type
- contextPath: RecordedFuture.Entities.score
  description: Entity Score
- contextPath: RecordedFuture.Entities.Evidence.ruleid
  description: Recorded Future Risk Rule ID
- contextPath: RecordedFuture.Entities.Evidence.timestamp
  description: Recorded Future Evidence Timestamp
- contextPath: RecordedFuture.Entities.Evidence.mitigation
  description: Recorded Future Evidence Mitigation
- contextPath: RecordedFuture.Entities.Evidence.description
  description: Recorded Future Evidence Description
- contextPath: RecordedFuture.Entities.Evidence.rule
  description: Recorded Future Risk Rule
- contextPath: RecordedFuture.Entities.Evidence.level
  description: Recorded Future Risk Rule Level
fromversion: 5.0.0
tests:
- No tests (auto formatted)
